### ISSUE TITLE
Can not open docs (too many redirects)

### ISSUE THREAD

**Issue by Tuginho** [spatie/laravel-site-search#40]
Hi, trying to read the docs but I'm receiving this error.
I've tried on other devices (and safari, chrome), as well on a other network and deleted cookies.

![image](https://github.com/spatie/laravel-site-search/assets/17098483/31ddf51b-0dd3-403e-8155-7155ba0bc32e)

**Comment by freekmurze** [comment]
Thanks for reporting, this has been fixed!

**Comment by Tuginho** [comment]
Hi Freek, unfortunately it still doesn't work. I have also cleared my DNS cache. I can open the introduction page, but other pages gives me the above error.
